/**
 * 🤖 AUTO-GENERATED RHEO MESH TYPES
 * Generated: 2026-02-06T22:06:12.183Z
 * 
 * This file is automatically generated by the Codegen cell.
 * DO NOT EDIT MANUALLY - changes will be overwritten.
 * 
 * To regenerate: The orchestrator triggers this on mesh changes.
 */

import type { Ai1Router } from './ai1/index';
import type { ChecklistRouter } from './checklist/index';
import type { LogRouter } from './log/index';
import type { InferRouter } from './protocols/example2';

export interface RheoMesh {
    ai: InferRouter<Ai1Router>['ai'];
    list: InferRouter<ChecklistRouter>['list'];
    log: InferRouter<LogRouter>['log'];
}

/**
 * Extract input type from a mesh procedure
 * Usage: MeshInput<'list', 'add'> gives you the exact input type
 */
export type MeshInput<
    TNamespace extends keyof RheoMesh,
    TProcedure extends keyof RheoMesh[TNamespace]
> = RheoMesh[TNamespace][TProcedure] extends { query: (input: infer I) => Promise<unknown> }
    ? I
    : RheoMesh[TNamespace][TProcedure] extends { mutate: (input: infer I) => Promise<unknown> }
    ? I
    : void;

/**
 * Extract output type from a mesh procedure
 * Usage: MeshOutput<'list', 'get'> gives you the exact return type
 */
export type MeshOutput<
    TNamespace extends keyof RheoMesh,
    TProcedure extends keyof RheoMesh[TNamespace]
> = RheoMesh[TNamespace][TProcedure] extends { query: (input?: unknown) => Promise<infer O> }
    ? O
    : RheoMesh[TNamespace][TProcedure] extends { mutate: (input?: unknown) => Promise<infer O> }
    ? O
    : unknown;

/**
 * Get all procedure names for a namespace
 * Usage: MeshProcedures<'list'> = 'add' | 'get' | 'complete' | ...
 */
export type MeshProcedures<TNamespace extends keyof RheoMesh> = keyof RheoMesh[TNamespace];

/**
 * Get all available namespaces
 * Usage: MeshNamespaces = 'list' | 'ai' | 'log' | ...
 */
export type MeshNamespaces = keyof RheoMesh;
